<?php
  session_start();
  include("../functions/functions.php");

  if (!isset($_SESSION['panitia'])) {
    echo "<center>Your session has invalid (timeout). Please <a href='index.php' target='_top'>Login</a> again";
  }
  else {
    echo "<html>\n";
    echo "<head>\n";
    echo "	<meta charset=\"UTF-8\">\n";
    echo "	<title>Basic CRUD Application - jQuery EasyUI CRUD Demo</title>\n";
    echo "  <link rel=\"stylesheet\" type=\"text/css\" href=\"jquery-easyui-1.5.2/themes/metro/easyui.css\">\n";
    echo "<link rel=\"stylesheet\" type=\"text/css\" href=\"jquery-easyui-1.5.2/themes/icon.css\">\n";
    echo "<script type=\"text/javascript\" src=\"jquery-easyui-1.5.2/jquery.min.js\"></script>\n";
    echo "<script type=\"text/javascript\" src=\"jquery-easyui-1.5.2/jquery.easyui.min.js\"></script>\n";
    echo "\n";
    echo "</head>\n";
    echo "<body>\n";
    echo "  <center>\n";
    echo "	<h2>Presensi Pemira 2017</h2>\n";
    echo "  <hr>\n";
    echo "  <form id=\"fm\" method=\"post\">\n";
    echo "\n";
    echo "			<div class=\"fitem\">\n";
    echo "      Prodi:  <select class=\"easyui-combobox\" id=\"prodi\" name=\"prodi\" style=\"width:15%;\">\n";
    echo "                <option value=\"Fisika\">Fisika</option>\n";
    echo "                <option value=\"Teknik Elektro\">Teknik Elektro</option>\n";
    echo "                <option value=\"Teknik Geofisika\">Teknik Geofisika</option>\n";
    echo "                <option value=\"Perencanaan Wilayah Dan Kota\">Perencanaan Wilayah Dan Kota</option>\n";
    echo "                <option value=\"Teknik Geomatika\">Teknik Geomatika</option>\n";
    echo "                <option value=\"Teknik Sipil\">Teknik Sipil</option>\n";
    echo "                <option value=\"Teknik Informatika\">Teknik Informatika</option>\n";
    echo "                <option value=\"Arsitektur\">Arsitektur</option>\n";
    echo "                <option value=\"Teknik Lingkungan\">Teknik Lingkungan</option>\n";
    echo "                <option value=\"Teknik Geologi\">Teknik Geologi</option>\n";
    echo "                <option value=\"Teknik Mesin\">Teknik Mesin</option>\n";
    echo "                <option value=\"Matematika\">Matematika</option>\n";
    echo "                <option value=\"Biologi\">Biologi</option>\n";
    echo "                <option value=\"Teknik Industri\">Teknik Industri</option>\n";
    echo "\n";
    echo "            </select>\n";
    echo "        Angkatan:    <select class=\"easyui-combobox\" id=\"angkatan\" name=\"angkatan\" style=\"width:10%;\">\n";
    echo "                    <option value=\"2012\">2012</option>\n";
    echo "                    <option value=\"2013\">2013</option>\n";
    echo "                    <option value=\"2014\">2014</option>\n";
    echo "                    <option value=\"2015\">2015</option>\n";
    echo "                    <option value=\"2016\">2016</option>\n";
    echo "                    <option value=\"2017\">2017</option>\n";
    echo "\n";
    echo "                </select>\n";
    echo "\n";
    echo "			</div>\n";
    echo "			<input type=\"hidden\" name=\"tombol\" id=\"update\" value=\"\">\n";
    echo "		</form>\n";
    echo "    <div id=\"dlg-buttons\">\n";
    echo "		<a href=\"javascript:void(0)\" class=\"easyui-linkbutton c6\" onclick=\"submit()\" style=\"width:90px\">Submit</a>\n";
    echo "		<a href=\"javascript:void(0)\" class=\"easyui-linkbutton c6\" onclick=\"clear()\" style=\"width:90px\">Clear</a>\n";
    echo "	</div>\n";
    echo "  <br>\n";
    echo "<table id=\"dg1\" title=\"My Users\" class=\"easyui-datagrid\" style=\"width:800px;height:350px\"\n";
    echo "        toolbar=\"#toolbar\"\n";
    echo "        rownumbers=\"true\"\n";
    echo "        fitColumns=\"true\" singleSelect=\"true\">\n";
    echo "    <thead>\n";
    echo "        <tr>\n";
    echo "            <th field=\"nim\" width=\"50\">NIM</th>\n";
    echo "            <th field=\"nama\" width=\"50\">Nama</th>\n";
    echo "            <th field=\"prodi\" width=\"50\">Program Studi</th>\n";
    echo "            <th field=\"angkatan\" width=\"50\">Angkatan</th>\n";
    echo "            <th field=\"lastlogin\" width=\"50\">Waktu Voting</th>\n";
    echo "        </tr>\n";
    echo "    </thead>\n";
    echo "</table>\n";
    echo "<div id=\"toolbar\">\n";
    echo "    <a href=\"javascript:void(0)\" class=\"easyui-linkbutton\" iconCls=\"icon-print\" plain=\"true\" onclick=\"pdf()\">Export to PDF</a>\n";
    echo "</div>\n";
    echo "\n";
    echo "<script type=\"text/javascript\">\n";
    echo "		var url;\n";
    echo "\n";
    echo "		$('#fm').form('clear');\n";
    echo "		function submit(){\n";
    echo "\n";
    echo "		//	$('#w').dialog('open').dialog('setTitle','Laporan Detail Penjualan');\n";
    echo "			var prodi = $('#prodi').val();\n";
    echo "			var angkatan = $('#angkatan').val();\n";
    echo "\n";
    echo "			$('#dg1').datagrid({\n";
    echo "				url:'getabsen.php?prodi='+prodi+'&angkatan='+angkatan\n";
    echo "\n";
    echo "			});\n";
    echo "			$('#dg1').datagrid('reload');\n";
    echo "\n";
    echo "		}\n";
    echo "\n";
    echo "		function clear(){\n";
    echo "			$('#fm').form('clear');\n";
    echo "		}\n";
    echo "\n";
    echo "    function pdf(){\n";
    echo "      var prodi1		= $(\"#prodi\").val();\n";
    echo "			var angkatan1	= $(\"#angkatan\").val();\n";
    echo "      window.open('pdf.php?prodi='+prodi1+'&angkatan='+angkatan1 );\n";
    echo "    }\n";
    echo "\n";
    echo "\n";
    echo "\n";
    echo "\n";
    echo "		function newUser(){\n";
    echo "//			document.getElementById(\"update\").value=\"Insert Data\";\n";
    echo "			var str = \"Insert Data\";\n";
    echo "			document.getElementById('update').value = str;\n";
    echo "			$('#nosup').numberbox('readonly',false)\n";
    echo "			$('#dlg').dialog('open').dialog('setTitle','Informasi Suplier');\n";
    echo "			$('#fm').form('clear');\n";
    echo "			url = 'suplierins.jsp';\n";
    echo "		}\n";
    echo "		function editUser(){\n";
    echo "//			document.getElementById(\"update\").value=\"Update Data\";\n";
    echo "			var str = \"Update Data\";\n";
    echo "			document.getElementById('update').value = str;\n";
    echo "			$('#nosup').numberbox('readonly',true)\n";
    echo "			var row = $('#dg').datagrid('getSelected');\n";
    echo "			if (row){\n";
    echo "				$('#dlg').dialog('open').dialog('setTitle','Informasi Suplier');\n";
    echo "				$('#fm').form('load',row);\n";
    echo "				url = 'suplierins.jsp';\n";
    echo "			}\n";
    echo "		}\n";
    echo "		function saveUser(){\n";
    echo "			$('#fm').form('submit',{\n";
    echo "				url: url,\n";
    echo "				onSubmit: function(){\n";
    echo "					return $(this).form('validate');\n";
    echo "				},\n";
    echo "				success: function(result){\n";
    echo "					var result = eval('('+result+')');\n";
    echo "					if (result.errorMsg){\n";
    echo "						$.messager.show({\n";
    echo "							title: 'Error',\n";
    echo "							msg: result.errorMsg\n";
    echo "						});\n";
    echo "					} else {\n";
    echo "						$('#dlg').dialog('close');		// close the dialog\n";
    echo "						$('#dg').datagrid('reload');	// reload the user data\n";
    echo "					}\n";
    echo "				}\n";
    echo "			});\n";
    echo "		}\n";
    echo "		function destroyUser(){\n";
    echo "			var row = $('#dg').datagrid('getSelected');\n";
    echo "			if (row){\n";
    echo "				var str = \"Delete Data\";\n";
    echo "				$.messager.confirm('Confirm','Are you sure you want to delete data?',function(r){\n";
    echo "					if (r){\n";
    echo "						$.post('suplierins.jsp',{kdtoko:row.kdtoko,tombol:str},function(result){\n";
    echo "							if (result.success){\n";
    echo "								$('#dg').datagrid('reload');	// reload the user data\n";
    echo "							} else {\n";
    echo "								$.messager.show({	// show error message\n";
    echo "									title: 'Error',\n";
    echo "									msg: result.errorMsg\n";
    echo "								});\n";
    echo "							}\n";
    echo "						},'json');\n";
    echo "					}\n";
    echo "				});\n";
    echo "			}\n";
    echo "		}\n";
    echo "	</script>\n";
    echo "	<style type=\"text/css\">\n";
    echo "		#fm{\n";
    echo "			margin:0;\n";
    echo "			padding:10px 30px;\n";
    echo "		}\n";
    echo "		.ftitle{\n";
    echo "			font-size:14px;\n";
    echo "			font-weight:bold;\n";
    echo "			padding:5px 0;\n";
    echo "			margin-bottom:10px;\n";
    echo "			border-bottom:1px solid #ccc;\n";
    echo "		}\n";
    echo "		.fitem{\n";
    echo "			margin-bottom:5px;\n";
    echo "		}\n";
    echo "		.fitem label{\n";
    echo "			display:inline-block;\n";
    echo "			width:80px;\n";
    echo "		}\n";
    echo "		.fitem input{\n";
    echo "			width:160px;\n";
    echo "		}\n";
    echo "	</style>\n";
    echo "</center>\n";
    echo "</body>\n";
    echo "</html>\n";
    echo "\n";
}
 ?>
